# Generated by Django 5.1.3 on 2024-11-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affirmations_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affirmation',
            old_name='text',
            new_name='affirmation',
        ),
    ]
