# Generated by Django 5.1.3 on 2024-11-21 14:37

from django.db import migrations
from django.apps import apps

def populate_user_profiles(apps, schema_editor):
    Affirmation = apps.get_model('affirmations_app', 'Affirmation')
    UserProfile = apps.get_model('affirmations_app', 'UserProfile')

    for affirmation in Affirmation.objects.all():
        user = affirmation.user
        if not UserProfile.objects.filter(user=user).exists():
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('affirmations_app', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(populate_user_profiles),
    ]